#!/usr/bin/env bash
set -euo pipefail

# install-as-service.sh
# Idempotent script to install ai_image_analyzer as a systemd service on Ubuntu
# Usage (as root or via sudo):
#  sudo ./deploy/install-as-service.sh [--user aiimage] [--install-dir /opt/ai_image_analyzer] [--repo https://github.com/<you>/ai_image_analyzer.git] [--branch main] [--bot-token TOKEN] [--bot-admin-id ID]

USER_NAME=aiimage
INSTALL_DIR=/opt/ai_image_analyzer
REPO=https://github.com/aadegtyarev/ai_image_analyzer.git
BRANCH=main
BOT_TOKEN=""
BOT_ADMIN_ID=""

print_usage(){
  cat <<EOF
Usage: sudo $0 [options]

Options:
  --user NAME           System user to run the service (default: ${USER_NAME})
  --install-dir PATH    Install directory (default: ${INSTALL_DIR})
  --repo URL            Git repo to clone (default: ${REPO})
  --branch BRANCH       Git branch to checkout (default: ${BRANCH})
  --bot-token TOKEN     (Optional) BOT_TOKEN to write into .env
  --bot-admin-id ID     (Optional) BOT_ADMIN_ID to write into .env
  -h, --help            Show this help
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --user) USER_NAME="$2"; shift 2;;
    --install-dir) INSTALL_DIR="$2"; shift 2;;
    --repo) REPO="$2"; shift 2;;
    --branch) BRANCH="$2"; shift 2;;
    --bot-token) BOT_TOKEN="$2"; shift 2;;
    --bot-admin-id) BOT_ADMIN_ID="$2"; shift 2;;
    -h|--help) print_usage; exit 0;;
    *) echo "Unknown arg: $1" >&2; print_usage; exit 1;;
  esac
done

if [ "$EUID" -ne 0 ]; then
  echo "This script must be run as root (sudo)." >&2
  exit 1
fi

echo "Install directory: ${INSTALL_DIR}"
echo "System user: ${USER_NAME}"
echo "Repo: ${REPO} (branch: ${BRANCH})"

# create system user if not exists
if id -u "${USER_NAME}" >/dev/null 2>&1; then
  echo "User ${USER_NAME} already exists"
else
  echo "Creating system user ${USER_NAME}..."
  useradd -m --system -s /usr/sbin/nologin "${USER_NAME}"
fi

# clone or update repo
if [ -d "${INSTALL_DIR}/.git" ]; then
  echo "Repository already exists, pulling latest..."
  git -C "${INSTALL_DIR}" fetch --all --prune
  git -C "${INSTALL_DIR}" checkout "${BRANCH}"
  git -C "${INSTALL_DIR}" pull --rebase origin "${BRANCH}"
else
  echo "Cloning repository to ${INSTALL_DIR}..."
  git clone --depth 1 --branch "${BRANCH}" "${REPO}" "${INSTALL_DIR}"
fi

# create venv
VENV_DIR="${INSTALL_DIR}/venv"
if [ -d "${VENV_DIR}" ]; then
  echo "Virtualenv exists at ${VENV_DIR}, skipping venv creation"
else
  echo "Creating virtualenv at ${VENV_DIR}..."
  python3 -m venv "${VENV_DIR}"
fi

echo "Installing requirements into venv (may take a while)..."
"${VENV_DIR}/bin/pip" install --upgrade pip
"${VENV_DIR}/bin/pip" install --upgrade -r "${INSTALL_DIR}/requirements.txt"

# prepare .env
ENV_FILE="${INSTALL_DIR}/.env"
if [ -f "${ENV_FILE}" ]; then
  echo ".env already exists, leaving untouched"
else
  echo "Creating .env from template..."
  cat > "${ENV_FILE}" <<EOF
# Generated by install-as-service.sh — edit values as needed
BOT_TOKEN=${BOT_TOKEN}
BOT_ADMIN_ID=${BOT_ADMIN_ID}
# Optional settings:
# PROMPT_FILE=prompts/art_analysis.txt
# PER_IMAGE_DEFAULT=0
EOF
  chown "${USER_NAME}":"${USER_NAME}" "${ENV_FILE}"
  chmod 600 "${ENV_FILE}"
  echo "Wrote ${ENV_FILE}. Please edit it to set BOT_TOKEN/BOT_ADMIN_ID if missing."
fi

# install systemd unit (templating paths)
UNIT_DEST=/etc/systemd/system/ai_image_analyzer.service
if [ -f "${UNIT_DEST}" ]; then
  echo "Systemd unit already exists at ${UNIT_DEST}, backing up to ${UNIT_DEST}.bak"
  cp -v "${UNIT_DEST}" "${UNIT_DEST}.bak"
fi

echo "Installing systemd unit..."
sed "s|/path/to/ai_image_analyzer|${INSTALL_DIR}|g; s|/path/to/venv|${VENV_DIR}|g; s|User=aiimage|User=${USER_NAME}|g; s|Group=aiimage|Group=${USER_NAME}|g; s|EnvironmentFile=/path/to/ai_image_analyzer/.env|EnvironmentFile=${ENV_FILE}|g" "${INSTALL_DIR}/deploy/ai_image_analyzer.service.example" > "${UNIT_DEST}"

chmod 644 "${UNIT_DEST}"

chown -R "${USER_NAME}":"${USER_NAME}" "${INSTALL_DIR}"

echo "Reloading systemd and enabling service..."
systemctl daemon-reload
systemctl enable --now ai_image_analyzer.service

echo "Installation complete. Service status:"
systemctl status --no-pager ai_image_analyzer.service || true

echo "To view logs: sudo journalctl -u ai_image_analyzer -f"

echo "If BOT_TOKEN was not set via --bot-token, edit ${ENV_FILE} as ${USER_NAME} and then run:"
echo "  sudo systemctl restart ai_image_analyzer.service"
